version: '2.1'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile    
    env_file:
      - ./src/.env   
    expose:
      - "8000"
    depends_on:
      db: 
        condition: service_completed_successfully
      redis: 
        condition: service_completed_successfully
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env
  db:
    image: postgres:13
    env_file:
      - ./src/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    expose:
      - "6379"
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres-data:
  redis-data: